services:
  - type: web
    name: disaster-relief-server
    runtime: node
    region: oregon
    rootDir: server
    buildCommand: npm install && npm run build
    startCommand: node src/index.js
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: CLIENT_URL
        value: https://disasterhelper.dpdns.org
      - key: ADMIN_EMAIL
        value: admin@relief.gov.in
      - key: ADMIN_PASSWORD
        sync: false
      - key: ADMIN_DISPLAY_NAME
        value: Administrator
